version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    deeptax:
      image: charlos1204/deep-oc-deeptax
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    deeptax-gpu:
      image: charlos1204/deep-oc-deeptax:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    deeptax-rclone:
      extends:
        service: deeptax
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
